apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenant-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: platform-infrastructure-services
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenant-infrastructure/__clustername__
  prune: true
  validation: client

