apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenant-apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: platform-apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenant-apps/__clustername__
  prune: true
  validation: client

