apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-streams-job-entitychanged-input
  namespace: kafka-streams
  labels:
    app: kafka-streams-job-entitychanged-input
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: kafka-streams-job-entitychanged-input
  template:
    metadata:
      labels:
        app: kafka-streams-job-entitychanged-input
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: kafka-streams-job-entitychanged-inputd
          image: __atlascontainerrepository__/boost-kafka-streams-edge:1.0.2 # {"$imagepolicy": "flux-system:kafka-streams-image-policy"} 
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-bootstrap.kafka:9092
            - name: CLASS
              value: soda.jobs.cloudevents.EntityChangedEventToResourceFieldDataJob
            - name: APPLICATION_ID
              value: streams-entitychanged-input
            - name: SOURCE_TOPIC
              value: entitychangedinput
            - name: OUTPUT_TOPIC
              value: data

            - name: AUTO_OFFSET_RESET_CONFIG
              value: latest 
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 10m
              memory: 128Mi
