apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform-apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: base
  path: ./apps/base
  prune: true
  validation: client

  patchesStrategicMerge:
    - ../../../apps/dockerdesktop/cluster-patch.yaml
    #- sealed-acr-pull-secret-patch.yaml
    #- sealed-device-connection-string-secret-patch.yaml
    - - ../../apps/dockerdesktop/persistent-volumes-patch.yaml

