---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tenant-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: tenant-source
  timeout: 20s
  url: ssh://git@github.com/neallclark/k8s-edge-tenant-config-template

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenant-source
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/dockerdesktop
  prune: true
  sourceRef:
    kind: GitRepository
    name: tenant-source

